using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class PokemonNamesList
{
    // Start is called before the first frame update


    public static List<string> maleOnlyPokemon = new List<string> {
        "Braviary",
        "Gallade",
        "Grimmsnarl",
        "Hitmonchan",
        "Hitmonlee",
        "Hitmontop",
        "Impidimp",
        "Landorus",
        "Latios",
        "Morgrem",
        "Mothim",
        "Nidoking",
        "Nidoran♂",
        "Nidorino",
        "Rufflet",
        "Sawk",
        "Tauros",
        "Throh",
        "Thundurus",
        "Tornadus",
        "Tyrogue",
        "Volbeat",
    };

    public static List<string> femaleOnlyPokemon = new List<string> {
        "Alcremie",
        "Blissey",
        "Bounsweet",
        "Chansey",
        "Cresselia",
        "Enamorus",
        "Flabebe",
        "Floette",
        "Florges",
        "Froslass",
        "Happiny",
        "Hatenna",
        "Hatterene",
        "Hattrem",
        "Illumise",
        "Jynx",
        "Kangaskhan",
        "Latias",
        "Lilligant",
        "Mandibuzz",
        "Milcery",
        "Miltank",
        "Nidoqueen",
        "Nidoran♀",
        "Nidorina",
        "Petilil",
        "Salazzle",
        "Smoochum",
        "Steenee",
        "Tsareena",
        "Vespiquen",
        "Vullaby",
        "Wormadam",
    };
    

    public static List<string> genderlessPokemon = new List<string> {
        "Magnemite",
        "Magneton",
        "Voltorb",
        "Electrode",
        "Staryu",
        "Starmie",
        "Porygon",
        "Porygon2",
        "Shedinja",
        "Lunatone",
        "Solrock",
        "Baltoy",
        "Claydol",
        "Beldum",
        "Metang",
        "Metagross",
        "Bronzor",
        "Bronzong",
        "Magnezone",
        "Porygon-Z",
        "Rotom",
        "Phione",
        "Manaphy",
        "Klink",
        "Klang",
        "Klinklang",
        "Cryogonal",
        "Golett",
        "Golurk",
        "Carbink",
        "Minior",
        "Dhelmise",
        "Sinistea",
        "Polteageist",
        "Falinks",
        "Ditto",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Mewtwo",
        "Mew",
        "Unown",
        "Raikou",
        "Entei",
        "Suicune",
        "Lugia",
        "Ho-Oh",
        "Celebi",
        "Celebi",
        "Regirock",
        "Regice",
        "Registeel",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys",
        "Uxie",
        "Mesprit",
        "Azelf",
        "Dialga",
        "Palkia",
        "Regigigas",
        "Giratina",
        "Darkrai",
        "Shaymin",
        "Arceus",
        "Victini",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Reshiram",
        "Zekrom",
        "Kyurem",
        "Keldeo",
        "Meloetta",
        "Genesect",
        "Xerneas",
        "Yveltal",
        "Zygarde",
        "Diancie",
        "Hoopa",
        "Volcanion",
        "Type: Null",
        "Silvally",
        "Tapu Koko",
        "Tapu Lele",
        "Tapu Bulu",
        "Tapu Fini",
        "Cosmog",
        "Cosmoem",
        "Solgaleo",
        "Lunala",
        "Nihilego",
        "Buzzwole",
        "Pheromosa",
        "Xurkitree",
        "Celesteela",
        "Kartana",
        "Guzzlord",
        "Necrozma",
        "Magearna",
        "Marshadow",
        "Poipole",
        "Naganadel",
        "Stakataka",
        "Blacephalon",
        "Zeraora",
        "Meltan",
        "Melmetal",
        "Dracozolt",
        "Arctozolt",
        "Dracovish",
        "Arctovish",
        "Zacian",
        "Zamazenta",
        "Eternatus",
        "Zarude",
        "Regieleki",
        "Regidrago",
        "Glastrier",
        "Spectrier",
        "Calyrex",
        };

    static Dictionary<string,List<Dictionary<string,int>>> pokemonList = new Dictionary<string,List<Dictionary<string,int>>> {
        {"A",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Abomasnow",460}},
            new Dictionary<string,int> {{"Abra",63}},
            new Dictionary<string,int> {{"Absol",359}},
            new Dictionary<string,int> {{"Accelgor",617}},
            new Dictionary<string,int> {{"Aegislash",681}},
            new Dictionary<string,int> {{"Aerodactyl",142}},
            new Dictionary<string,int> {{"Aggron",306}},
            new Dictionary<string,int> {{"Aipom",190}},
            new Dictionary<string,int> {{"Alakazam",65}},
            new Dictionary<string,int> {{"Alcremie",869}},
            new Dictionary<string,int> {{"Alomomola",594}},
            new Dictionary<string,int> {{"Altaria",334}},
            new Dictionary<string,int> {{"Amaura",698}},
            new Dictionary<string,int> {{"Ambipom",424}},
            new Dictionary<string,int> {{"Amoonguss",591}},
            new Dictionary<string,int> {{"Ampharos",181}},
            new Dictionary<string,int> {{"Anorith",347}},
            new Dictionary<string,int> {{"Appletun",842}},
            new Dictionary<string,int> {{"Applin",840}},
            new Dictionary<string,int> {{"Araquanid",752}},
            new Dictionary<string,int> {{"Arbok",24}},
            new Dictionary<string,int> {{"Arcanine",59}},
            new Dictionary<string,int> {{"Arceus",493}},
            new Dictionary<string,int> {{"Archen",566}},
            new Dictionary<string,int> {{"Archeops",567}},
            new Dictionary<string,int> {{"Arctovish",883}},
            new Dictionary<string,int> {{"Arctozolt",881}},
            new Dictionary<string,int> {{"Ariados",168}},
            new Dictionary<string,int> {{"Armaldo",348}},
            new Dictionary<string,int> {{"Aromatisse",683}},
            new Dictionary<string,int> {{"Aron",304}},
            new Dictionary<string,int> {{"Arrokuda",846}},
            new Dictionary<string,int> {{"Articuno",144}},
            new Dictionary<string,int> {{"Audino",531}},
            new Dictionary<string,int> {{"Aurorus",699}},
            new Dictionary<string,int> {{"Avalugg",713}},
            new Dictionary<string,int> {{"Axew",610}},
            new Dictionary<string,int> {{"Azelf",482}},
            new Dictionary<string,int> {{"Azumarill",184}},
            new Dictionary<string,int> {{"Azurill",298}},
            }
        },
        {"B",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Bagon",371}},
            new Dictionary<string,int> {{"Baltoy",343}},
            new Dictionary<string,int> {{"Banette",354}},
            new Dictionary<string,int> {{"Barbaracle",689}},
            new Dictionary<string,int> {{"Barboach",339}},
            new Dictionary<string,int> {{"Barraskewda",847}},
            new Dictionary<string,int> {{"Basculegion",902}},
            new Dictionary<string,int> {{"Basculin",550}},
            new Dictionary<string,int> {{"Bastiodon",411}},
            new Dictionary<string,int> {{"Bayleef",153}},
            new Dictionary<string,int> {{"Beartic",614}},
            new Dictionary<string,int> {{"Beautifly",267}},
            new Dictionary<string,int> {{"Beedrill",15}},
            new Dictionary<string,int> {{"Beheeyem",606}},
            new Dictionary<string,int> {{"Beldum",374}},
            new Dictionary<string,int> {{"Bellossom",182}},
            new Dictionary<string,int> {{"Bellsprout",69}},
            new Dictionary<string,int> {{"Bergmite",712}},
            new Dictionary<string,int> {{"Bewear",760}},
            new Dictionary<string,int> {{"Bibarel",400}},
            new Dictionary<string,int> {{"Bidoof",399}},
            new Dictionary<string,int> {{"Binacle",688}},
            new Dictionary<string,int> {{"Bisharp",625}},
            new Dictionary<string,int> {{"Blacephalon",806}},
            new Dictionary<string,int> {{"Blastoise",9}},
            new Dictionary<string,int> {{"Blaziken",257}},
            new Dictionary<string,int> {{"Blipbug",824}},
            new Dictionary<string,int> {{"Blissey",242}},
            new Dictionary<string,int> {{"Blitzle",522}},
            new Dictionary<string,int> {{"Boldore",525}},
            new Dictionary<string,int> {{"Boltund",836}},
            new Dictionary<string,int> {{"Bonsly",438}},
            new Dictionary<string,int> {{"Bouffalant",626}},
            new Dictionary<string,int> {{"Bounsweet",761}},
            new Dictionary<string,int> {{"Braixen",654}},
            new Dictionary<string,int> {{"Braviary",628}},
            new Dictionary<string,int> {{"Breloom",286}},
            new Dictionary<string,int> {{"Brionne",729}},
            new Dictionary<string,int> {{"Bronzong",437}},
            new Dictionary<string,int> {{"Bronzor",436}},
            new Dictionary<string,int> {{"Bruxish",779}},
            new Dictionary<string,int> {{"Budew",406}},
            new Dictionary<string,int> {{"Buizel",418}},
            new Dictionary<string,int> {{"Bulbasaur",1}},
            new Dictionary<string,int> {{"Buneary",427}},
            new Dictionary<string,int> {{"Bunnelby",659}},
            new Dictionary<string,int> {{"Burmy",412}},
            new Dictionary<string,int> {{"Butterfree",12}},
            new Dictionary<string,int> {{"Buzzwole",794}},
            }
        },
        {"C",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Cacnea",331}},
            new Dictionary<string,int> {{"Cacturne",332}},
            new Dictionary<string,int> {{"Calyrex",898}},
            new Dictionary<string,int> {{"Camerupt",323}},
            new Dictionary<string,int> {{"Carbink",703}},
            new Dictionary<string,int> {{"Carkol",838}},
            new Dictionary<string,int> {{"Carnivine",455}},
            new Dictionary<string,int> {{"Carracosta",565}},
            new Dictionary<string,int> {{"Carvanha",318}},
            new Dictionary<string,int> {{"Cascoon",268}},
            new Dictionary<string,int> {{"Castform",351}},
            new Dictionary<string,int> {{"Caterpie",10}},
            new Dictionary<string,int> {{"Celebi",251}},
            new Dictionary<string,int> {{"Celesteela",797}},
            new Dictionary<string,int> {{"Centiskorch",851}},
            new Dictionary<string,int> {{"Chandelure",609}},
            new Dictionary<string,int> {{"Chansey",113}},
            new Dictionary<string,int> {{"Charizard",6}},
            new Dictionary<string,int> {{"Charjabug",737}},
            new Dictionary<string,int> {{"Charmander",4}},
            new Dictionary<string,int> {{"Charmeleon",5}},
            new Dictionary<string,int> {{"Chatot",441}},
            new Dictionary<string,int> {{"Cherrim",421}},
            new Dictionary<string,int> {{"Cherubi",420}},
            new Dictionary<string,int> {{"Chesnaught",652}},
            new Dictionary<string,int> {{"Chespin",650}},
            new Dictionary<string,int> {{"Chewtle",833}},
            new Dictionary<string,int> {{"Chikorita",152}},
            new Dictionary<string,int> {{"Chimchar",390}},
            new Dictionary<string,int> {{"Chimecho",358}},
            new Dictionary<string,int> {{"Chinchou",170}},
            new Dictionary<string,int> {{"Chingling",433}},
            new Dictionary<string,int> {{"Cinccino",573}},
            new Dictionary<string,int> {{"Cinderace",815}},
            new Dictionary<string,int> {{"Clamperl",366}},
            new Dictionary<string,int> {{"Clauncher",692}},
            new Dictionary<string,int> {{"Clawitzer",693}},
            new Dictionary<string,int> {{"Claydol",344}},
            new Dictionary<string,int> {{"Clefable",36}},
            new Dictionary<string,int> {{"Clefairy",35}},
            new Dictionary<string,int> {{"Cleffa",173}},
            new Dictionary<string,int> {{"Clobbopus",852}},
            new Dictionary<string,int> {{"Cloyster",91}},
            new Dictionary<string,int> {{"Coalossal",839}},
            new Dictionary<string,int> {{"Cobalion",638}},
            new Dictionary<string,int> {{"Cofagrigus",563}},
            new Dictionary<string,int> {{"Combee",415}},
            new Dictionary<string,int> {{"Combusken",256}},
            new Dictionary<string,int> {{"Comfey",764}},
            new Dictionary<string,int> {{"Conkeldurr",534}},
            new Dictionary<string,int> {{"Copperajah",879}},
            new Dictionary<string,int> {{"Corphish",341}},
            new Dictionary<string,int> {{"Corsola",222}},
            new Dictionary<string,int> {{"Corviknight",823}},
            new Dictionary<string,int> {{"Corvisquire",822}},
            new Dictionary<string,int> {{"Cosmoem",790}},
            new Dictionary<string,int> {{"Cosmog",789}},
            new Dictionary<string,int> {{"Cottonee",546}},
            new Dictionary<string,int> {{"Crabominable",740}},
            new Dictionary<string,int> {{"Crabrawler",739}},
            new Dictionary<string,int> {{"Cradily",346}},
            new Dictionary<string,int> {{"Cramorant",845}},
            new Dictionary<string,int> {{"Cranidos",408}},
            new Dictionary<string,int> {{"Crawdaunt",342}},
            new Dictionary<string,int> {{"Cresselia",488}},
            new Dictionary<string,int> {{"Croagunk",453}},
            new Dictionary<string,int> {{"Crobat",169}},
            new Dictionary<string,int> {{"Croconaw",159}},
            new Dictionary<string,int> {{"Crustle",558}},
            new Dictionary<string,int> {{"Cryogonal",615}},
            new Dictionary<string,int> {{"Cubchoo",613}},
            new Dictionary<string,int> {{"Cubone",104}},
            new Dictionary<string,int> {{"Cufant",878}},
            new Dictionary<string,int> {{"Cursola",864}},
            new Dictionary<string,int> {{"Cutiefly",742}},
            new Dictionary<string,int> {{"Cyndaquil",155}},
            }
        },
        {"D",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Darkrai",491}},
            new Dictionary<string,int> {{"Darmanitan",555}},
            new Dictionary<string,int> {{"Dartrix",723}},
            new Dictionary<string,int> {{"Darumaka",554}},
            new Dictionary<string,int> {{"Decidueye",724}},
            new Dictionary<string,int> {{"Dedenne",702}},
            new Dictionary<string,int> {{"Deerling",585}},
            new Dictionary<string,int> {{"Deino",633}},
            new Dictionary<string,int> {{"Delcatty",301}},
            new Dictionary<string,int> {{"Delibird",225}},
            new Dictionary<string,int> {{"Delphox",655}},
            new Dictionary<string,int> {{"Deoxys",386}},
            new Dictionary<string,int> {{"Dewgong",87}},
            new Dictionary<string,int> {{"Dewott",502}},
            new Dictionary<string,int> {{"Dewpider",751}},
            new Dictionary<string,int> {{"Dhelmise",781}},
            new Dictionary<string,int> {{"Dialga",483}},
            new Dictionary<string,int> {{"Diancie",719}},
            new Dictionary<string,int> {{"Diggersby",660}},
            new Dictionary<string,int> {{"Diglett",50}},
            new Dictionary<string,int> {{"Ditto",132}},
            new Dictionary<string,int> {{"Dodrio",85}},
            new Dictionary<string,int> {{"Doduo",84}},
            new Dictionary<string,int> {{"Donphan",232}},
            new Dictionary<string,int> {{"Dottler",825}},
            new Dictionary<string,int> {{"Doublade",680}},
            new Dictionary<string,int> {{"Dracovish",882}},
            new Dictionary<string,int> {{"Dracozolt",880}},
            new Dictionary<string,int> {{"Dragalge",691}},
            new Dictionary<string,int> {{"Dragapult",887}},
            new Dictionary<string,int> {{"Dragonair",148}},
            new Dictionary<string,int> {{"Dragonite",149}},
            new Dictionary<string,int> {{"Drakloak",886}},
            new Dictionary<string,int> {{"Drampa",780}},
            new Dictionary<string,int> {{"Drapion",452}},
            new Dictionary<string,int> {{"Dratini",147}},
            new Dictionary<string,int> {{"Drednaw",834}},
            new Dictionary<string,int> {{"Dreepy",885}},
            new Dictionary<string,int> {{"Drifblim",426}},
            new Dictionary<string,int> {{"Drifloon",425}},
            new Dictionary<string,int> {{"Drilbur",529}},
            new Dictionary<string,int> {{"Drizzile",817}},
            new Dictionary<string,int> {{"Drowzee",96}},
            new Dictionary<string,int> {{"Druddigon",621}},
            new Dictionary<string,int> {{"Dubwool",832}},
            new Dictionary<string,int> {{"Ducklett",580}},
            new Dictionary<string,int> {{"Dugtrio",51}},
            new Dictionary<string,int> {{"Dunsparce",206}},
            new Dictionary<string,int> {{"Duosion",578}},
            new Dictionary<string,int> {{"Duraludon",884}},
            new Dictionary<string,int> {{"Durant",632}},
            new Dictionary<string,int> {{"Dusclops",356}},
            new Dictionary<string,int> {{"Dusknoir",477}},
            new Dictionary<string,int> {{"Duskull",355}},
            new Dictionary<string,int> {{"Dustox",269}},
            new Dictionary<string,int> {{"Dwebble",557}},
            }
        },
        {"E",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Eelektrik",603}},
            new Dictionary<string,int> {{"Eelektross",604}},
            new Dictionary<string,int> {{"Eevee",133}},
            new Dictionary<string,int> {{"Eiscue",875}},
            new Dictionary<string,int> {{"Ekans",23}},
            new Dictionary<string,int> {{"Eldegoss",830}},
            new Dictionary<string,int> {{"Electabuzz",125}},
            new Dictionary<string,int> {{"Electivire",466}},
            new Dictionary<string,int> {{"Electrike",309}},
            new Dictionary<string,int> {{"Electrode",101}},
            new Dictionary<string,int> {{"Elekid",239}},
            new Dictionary<string,int> {{"Elgyem",605}},
            new Dictionary<string,int> {{"Emboar",500}},
            new Dictionary<string,int> {{"Emolga",587}},
            new Dictionary<string,int> {{"Empoleon",395}},
            new Dictionary<string,int> {{"Enamorus",905}},
            new Dictionary<string,int> {{"Entei",244}},
            new Dictionary<string,int> {{"Escavalier",589}},
            new Dictionary<string,int> {{"Espeon",196}},
            new Dictionary<string,int> {{"Espurr",677}},
            new Dictionary<string,int> {{"Eternatus",890}},
            new Dictionary<string,int> {{"Excadrill",530}},
            new Dictionary<string,int> {{"Exeggcute",102}},
            new Dictionary<string,int> {{"Exeggutor",103}},
            new Dictionary<string,int> {{"Exploud",295}},
            }
        },
        {"F",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Falinks",870}},
            new Dictionary<string,int> {{"Farfetch'd",83}},
            new Dictionary<string,int> {{"Fearow",22}},
            new Dictionary<string,int> {{"Feebas",349}},
            new Dictionary<string,int> {{"Fennekin",653}},
            new Dictionary<string,int> {{"Feraligatr",160}},
            new Dictionary<string,int> {{"Ferroseed",597}},
            new Dictionary<string,int> {{"Ferrothorn",598}},
            new Dictionary<string,int> {{"Finneon",456}},
            new Dictionary<string,int> {{"Flaaffy",180}},
            new Dictionary<string,int> {{"Flabebe",669}},
            new Dictionary<string,int> {{"Flapple",841}},
            new Dictionary<string,int> {{"Flareon",136}},
            new Dictionary<string,int> {{"Fletchinder",662}},
            new Dictionary<string,int> {{"Fletchling",661}},
            new Dictionary<string,int> {{"Floatzel",419}},
            new Dictionary<string,int> {{"Floette",670}},
            new Dictionary<string,int> {{"Florges",671}},
            new Dictionary<string,int> {{"Flygon",330}},
            new Dictionary<string,int> {{"Fomantis",753}},
            new Dictionary<string,int> {{"Foongus",590}},
            new Dictionary<string,int> {{"Forretress",205}},
            new Dictionary<string,int> {{"Fraxure",611}},
            new Dictionary<string,int> {{"Frillish",592}},
            new Dictionary<string,int> {{"Froakie",656}},
            new Dictionary<string,int> {{"Frogadier",657}},
            new Dictionary<string,int> {{"Froslass",478}},
            new Dictionary<string,int> {{"Frosmoth",873}},
            new Dictionary<string,int> {{"Furfrou",676}},
            new Dictionary<string,int> {{"Furret",162}},
            }
        },
        {"G",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Gabite",444}},
            new Dictionary<string,int> {{"Gallade",475}},
            new Dictionary<string,int> {{"Galvantula",596}},
            new Dictionary<string,int> {{"Garbodor",569}},
            new Dictionary<string,int> {{"Garchomp",445}},
            new Dictionary<string,int> {{"Gardevoir",282}},
            new Dictionary<string,int> {{"Gastly",92}},
            new Dictionary<string,int> {{"Gastrodon",423}},
            new Dictionary<string,int> {{"Genesect",649}},
            new Dictionary<string,int> {{"Gengar",94}},
            new Dictionary<string,int> {{"Geodude",74}},
            new Dictionary<string,int> {{"Gible",443}},
            new Dictionary<string,int> {{"Gigalith",526}},
            new Dictionary<string,int> {{"Girafarig",203}},
            new Dictionary<string,int> {{"Giratina",487}},
            new Dictionary<string,int> {{"Glaceon",471}},
            new Dictionary<string,int> {{"Glalie",362}},
            new Dictionary<string,int> {{"Glameow",431}},
            new Dictionary<string,int> {{"Glastrier",896}},
            new Dictionary<string,int> {{"Gligar",207}},
            new Dictionary<string,int> {{"Gliscor",472}},
            new Dictionary<string,int> {{"Gloom",44}},
            new Dictionary<string,int> {{"Gogoat",673}},
            new Dictionary<string,int> {{"Golbat",42}},
            new Dictionary<string,int> {{"Goldeen",118}},
            new Dictionary<string,int> {{"Golduck",55}},
            new Dictionary<string,int> {{"Golem",76}},
            new Dictionary<string,int> {{"Golett",622}},
            new Dictionary<string,int> {{"Golisopod",768}},
            new Dictionary<string,int> {{"Golurk",623}},
            new Dictionary<string,int> {{"Goodra",706}},
            new Dictionary<string,int> {{"Goomy",704}},
            new Dictionary<string,int> {{"Gorebyss",368}},
            new Dictionary<string,int> {{"Gossifleur",829}},
            new Dictionary<string,int> {{"Gothita",574}},
            new Dictionary<string,int> {{"Gothitelle",576}},
            new Dictionary<string,int> {{"Gothorita",575}},
            new Dictionary<string,int> {{"Gourgeist",711}},
            new Dictionary<string,int> {{"Granbull",210}},
            new Dictionary<string,int> {{"Grapploct",853}},
            new Dictionary<string,int> {{"Graveler",75}},
            new Dictionary<string,int> {{"Greedent",820}},
            new Dictionary<string,int> {{"Greninja",658}},
            new Dictionary<string,int> {{"Grimer",88}},
            new Dictionary<string,int> {{"Grimmsnarl",861}},
            new Dictionary<string,int> {{"Grookey",810}},
            new Dictionary<string,int> {{"Grotle",388}},
            new Dictionary<string,int> {{"Groudon",383}},
            new Dictionary<string,int> {{"Grovyle",253}},
            new Dictionary<string,int> {{"Growlithe",58}},
            new Dictionary<string,int> {{"Grubbin",736}},
            new Dictionary<string,int> {{"Grumpig",326}},
            new Dictionary<string,int> {{"Gulpin",316}},
            new Dictionary<string,int> {{"Gumshoos",735}},
            new Dictionary<string,int> {{"Gurdurr",533}},
            new Dictionary<string,int> {{"Guzzlord",799}},
            new Dictionary<string,int> {{"Gyarados",130}},
            }
        },
        {"H",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Hakamo-o",783}},
            new Dictionary<string,int> {{"Happiny",440}},
            new Dictionary<string,int> {{"Hariyama",297}},
            new Dictionary<string,int> {{"Hatenna",856}},
            new Dictionary<string,int> {{"Hatterene",858}},
            new Dictionary<string,int> {{"Hattrem",857}},
            new Dictionary<string,int> {{"Haunter",93}},
            new Dictionary<string,int> {{"Hawlucha",701}},
            new Dictionary<string,int> {{"Haxorus",612}},
            new Dictionary<string,int> {{"Heatmor",631}},
            new Dictionary<string,int> {{"Heatran",485}},
            new Dictionary<string,int> {{"Heliolisk",695}},
            new Dictionary<string,int> {{"Helioptile",694}},
            new Dictionary<string,int> {{"Heracross",214}},
            new Dictionary<string,int> {{"Herdier",507}},
            new Dictionary<string,int> {{"Hippopotas",449}},
            new Dictionary<string,int> {{"Hippowdon",450}},
            new Dictionary<string,int> {{"Hitmonchan",107}},
            new Dictionary<string,int> {{"Hitmonlee",106}},
            new Dictionary<string,int> {{"Hitmontop",237}},
            new Dictionary<string,int> {{"Ho-Oh",250}},
            new Dictionary<string,int> {{"Honchkrow",430}},
            new Dictionary<string,int> {{"Honedge",679}},
            new Dictionary<string,int> {{"Hoopa",720}},
            new Dictionary<string,int> {{"Hoothoot",163}},
            new Dictionary<string,int> {{"Hoppip",187}},
            new Dictionary<string,int> {{"Horsea",116}},
            new Dictionary<string,int> {{"Houndoom",229}},
            new Dictionary<string,int> {{"Houndour",228}},
            new Dictionary<string,int> {{"Huntail",367}},
            new Dictionary<string,int> {{"Hydreigon",635}},
            new Dictionary<string,int> {{"Hypno",97}},
            }
        },
        {"I",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Igglybuff",174}},
            new Dictionary<string,int> {{"Illumise",314}},
            new Dictionary<string,int> {{"Impidimp",859}},
            new Dictionary<string,int> {{"Incineroar",727}},
            new Dictionary<string,int> {{"Indeedee",876}},
            new Dictionary<string,int> {{"Infernape",392}},
            new Dictionary<string,int> {{"Inkay",686}},
            new Dictionary<string,int> {{"Inteleon",818}},
            new Dictionary<string,int> {{"Ivysaur",2}},
            }
        },
        {"J",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Jangmo-o",782}},
            new Dictionary<string,int> {{"Jellicent",593}},
            new Dictionary<string,int> {{"Jigglypuff",39}},
            new Dictionary<string,int> {{"Jirachi",385}},
            new Dictionary<string,int> {{"Jolteon",135}},
            new Dictionary<string,int> {{"Joltik",595}},
            new Dictionary<string,int> {{"Jumpluff",189}},
            new Dictionary<string,int> {{"Jynx",124}},
            }
        },
        {"K",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Kabuto",140}},
            new Dictionary<string,int> {{"Kabutops",141}},
            new Dictionary<string,int> {{"Kadabra",64}},
            new Dictionary<string,int> {{"Kakuna",14}},
            new Dictionary<string,int> {{"Kangaskhan",115}},
            new Dictionary<string,int> {{"Karrablast",588}},
            new Dictionary<string,int> {{"Kartana",798}},
            new Dictionary<string,int> {{"Kecleon",352}},
            new Dictionary<string,int> {{"Keldeo",647}},
            new Dictionary<string,int> {{"Kingdra",230}},
            new Dictionary<string,int> {{"Kingler",99}},
            new Dictionary<string,int> {{"Kirlia",281}},
            new Dictionary<string,int> {{"Klang",600}},
            new Dictionary<string,int> {{"Kleavor",900}},
            new Dictionary<string,int> {{"Klefki",707}},
            new Dictionary<string,int> {{"Klink",599}},
            new Dictionary<string,int> {{"Klinklang",601}},
            new Dictionary<string,int> {{"Koffing",109}},
            new Dictionary<string,int> {{"Komala",775}},
            new Dictionary<string,int> {{"Kommo-o",784}},
            new Dictionary<string,int> {{"Krabby",98}},
            new Dictionary<string,int> {{"Kricketot",401}},
            new Dictionary<string,int> {{"Kricketune",402}},
            new Dictionary<string,int> {{"Krokorok",552}},
            new Dictionary<string,int> {{"Krookodile",553}},
            new Dictionary<string,int> {{"Kubfu",891}},
            new Dictionary<string,int> {{"Kyogre",382}},
            new Dictionary<string,int> {{"Kyurem",646}},
            }
        },
        {"L",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Lairon",305}},
            new Dictionary<string,int> {{"Lampent",608}},
            new Dictionary<string,int> {{"Landorus",645}},
            new Dictionary<string,int> {{"Lanturn",171}},
            new Dictionary<string,int> {{"Lapras",131}},
            new Dictionary<string,int> {{"Larvesta",636}},
            new Dictionary<string,int> {{"Larvitar",246}},
            new Dictionary<string,int> {{"Latias",380}},
            new Dictionary<string,int> {{"Latios",381}},
            new Dictionary<string,int> {{"Leafeon",470}},
            new Dictionary<string,int> {{"Leavanny",542}},
            new Dictionary<string,int> {{"Ledian",166}},
            new Dictionary<string,int> {{"Ledyba",165}},
            new Dictionary<string,int> {{"Lickilicky",463}},
            new Dictionary<string,int> {{"Lickitung",108}},
            new Dictionary<string,int> {{"Liepard",510}},
            new Dictionary<string,int> {{"Lileep",345}},
            new Dictionary<string,int> {{"Lilligant",549}},
            new Dictionary<string,int> {{"Lillipup",506}},
            new Dictionary<string,int> {{"Linoone",264}},
            new Dictionary<string,int> {{"Litleo",667}},
            new Dictionary<string,int> {{"Litten",725}},
            new Dictionary<string,int> {{"Litwick",607}},
            new Dictionary<string,int> {{"Lombre",271}},
            new Dictionary<string,int> {{"Lopunny",428}},
            new Dictionary<string,int> {{"Lotad",270}},
            new Dictionary<string,int> {{"Loudred",294}},
            new Dictionary<string,int> {{"Lucario",448}},
            new Dictionary<string,int> {{"Ludicolo",272}},
            new Dictionary<string,int> {{"Lugia",249}},
            new Dictionary<string,int> {{"Lumineon",457}},
            new Dictionary<string,int> {{"Lunala",792}},
            new Dictionary<string,int> {{"Lunatone",337}},
            new Dictionary<string,int> {{"Lurantis",754}},
            new Dictionary<string,int> {{"Luvdisc",370}},
            new Dictionary<string,int> {{"Luxio",404}},
            new Dictionary<string,int> {{"Luxray",405}},
            new Dictionary<string,int> {{"Lycanroc",745}},
            }
        },
        {"M",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Machamp",68}},
            new Dictionary<string,int> {{"Machoke",67}},
            new Dictionary<string,int> {{"Machop",66}},
            new Dictionary<string,int> {{"Magby",240}},
            new Dictionary<string,int> {{"Magcargo",219}},
            new Dictionary<string,int> {{"Magearna",801}},
            new Dictionary<string,int> {{"Magikarp",129}},
            new Dictionary<string,int> {{"Magmar",126}},
            new Dictionary<string,int> {{"Magmortar",467}},
            new Dictionary<string,int> {{"Magnemite",81}},
            new Dictionary<string,int> {{"Magneton",82}},
            new Dictionary<string,int> {{"Magnezone",462}},
            new Dictionary<string,int> {{"Makuhita",296}},
            new Dictionary<string,int> {{"Malamar",687}},
            new Dictionary<string,int> {{"Mamoswine",473}},
            new Dictionary<string,int> {{"Manaphy",490}},
            new Dictionary<string,int> {{"Mandibuzz",630}},
            new Dictionary<string,int> {{"Manectric",310}},
            new Dictionary<string,int> {{"Mankey",56}},
            new Dictionary<string,int> {{"Mantine",226}},
            new Dictionary<string,int> {{"Mantyke",458}},
            new Dictionary<string,int> {{"Maractus",556}},
            new Dictionary<string,int> {{"Mareanie",747}},
            new Dictionary<string,int> {{"Mareep",179}},
            new Dictionary<string,int> {{"Marill",183}},
            new Dictionary<string,int> {{"Marowak",105}},
            new Dictionary<string,int> {{"Marshadow",802}},
            new Dictionary<string,int> {{"Marshtomp",259}},
            new Dictionary<string,int> {{"Masquerain",284}},
            new Dictionary<string,int> {{"Mawile",303}},
            new Dictionary<string,int> {{"Medicham",308}},
            new Dictionary<string,int> {{"Meditite",307}},
            new Dictionary<string,int> {{"Meganium",154}},
            new Dictionary<string,int> {{"Melmetal",809}},
            new Dictionary<string,int> {{"Meloetta",648}},
            new Dictionary<string,int> {{"Meltan",808}},
            new Dictionary<string,int> {{"Meowstic",678}},
            new Dictionary<string,int> {{"Meowth",52}},
            new Dictionary<string,int> {{"Mesprit",481}},
            new Dictionary<string,int> {{"Metagross",376}},
            new Dictionary<string,int> {{"Metang",375}},
            new Dictionary<string,int> {{"Metapod",11}},
            new Dictionary<string,int> {{"Mew",151}},
            new Dictionary<string,int> {{"Mewtwo",150}},
            new Dictionary<string,int> {{"Mienfoo",619}},
            new Dictionary<string,int> {{"Mienshao",620}},
            new Dictionary<string,int> {{"Mightyena",262}},
            new Dictionary<string,int> {{"Milcery",868}},
            new Dictionary<string,int> {{"Milotic",350}},
            new Dictionary<string,int> {{"Miltank",241}},
            new Dictionary<string,int> {{"Mime Jr.",439}},
            new Dictionary<string,int> {{"Mimikyu",778}},
            new Dictionary<string,int> {{"Minccino",572}},
            new Dictionary<string,int> {{"Minior",774}},
            new Dictionary<string,int> {{"Minun",312}},
            new Dictionary<string,int> {{"Misdreavus",200}},
            new Dictionary<string,int> {{"Mismagius",429}},
            new Dictionary<string,int> {{"Moltres",146}},
            new Dictionary<string,int> {{"Monferno",391}},
            new Dictionary<string,int> {{"Morelull",755}},
            new Dictionary<string,int> {{"Morgrem",860}},
            new Dictionary<string,int> {{"Morpeko",877}},
            new Dictionary<string,int> {{"Mothim",414}},
            new Dictionary<string,int> {{"Mr. Mime",122}},
            new Dictionary<string,int> {{"Mr. Rime",866}},
            new Dictionary<string,int> {{"Mudbray",749}},
            new Dictionary<string,int> {{"Mudkip",258}},
            new Dictionary<string,int> {{"Mudsdale",750}},
            new Dictionary<string,int> {{"Muk",89}},
            new Dictionary<string,int> {{"Munchlax",446}},
            new Dictionary<string,int> {{"Munna",517}},
            new Dictionary<string,int> {{"Murkrow",198}},
            new Dictionary<string,int> {{"Musharna",518}},
            }
        },
        {"N",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Naganadel",804}},
            new Dictionary<string,int> {{"Natu",177}},
            new Dictionary<string,int> {{"Necrozma",800}},
            new Dictionary<string,int> {{"Nickit",827}},
            new Dictionary<string,int> {{"Nidoking",34}},
            new Dictionary<string,int> {{"Nidoqueen",31}},
            new Dictionary<string,int> {{"Nidoran♀",29}},
            new Dictionary<string,int> {{"Nidoran♂",32}},
            new Dictionary<string,int> {{"Nidorina",30}},
            new Dictionary<string,int> {{"Nidorino",33}},
            new Dictionary<string,int> {{"Nihilego",793}},
            new Dictionary<string,int> {{"Nincada",290}},
            new Dictionary<string,int> {{"Ninetales",38}},
            new Dictionary<string,int> {{"Ninjask",291}},
            new Dictionary<string,int> {{"Noctowl",164}},
            new Dictionary<string,int> {{"Noibat",714}},
            new Dictionary<string,int> {{"Noivern",715}},
            new Dictionary<string,int> {{"Nosepass",299}},
            new Dictionary<string,int> {{"Numel",322}},
            new Dictionary<string,int> {{"Nuzleaf",274}},
            }
        },
        {"O",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Obstagoon",862}},
            new Dictionary<string,int> {{"Octillery",224}},
            new Dictionary<string,int> {{"Oddish",43}},
            new Dictionary<string,int> {{"Omanyte",138}},
            new Dictionary<string,int> {{"Omastar",139}},
            new Dictionary<string,int> {{"Onix",95}},
            new Dictionary<string,int> {{"Oranguru",765}},
            new Dictionary<string,int> {{"Orbeetle",826}},
            new Dictionary<string,int> {{"Oricorio",741}},
            new Dictionary<string,int> {{"Oshawott",501}},
            new Dictionary<string,int> {{"Overqwil",904}},
            }
        },
        {"P",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Pachirisu",417}},
            new Dictionary<string,int> {{"Palkia",484}},
            new Dictionary<string,int> {{"Palossand",770}},
            new Dictionary<string,int> {{"Palpitoad",536}},
            new Dictionary<string,int> {{"Pancham",674}},
            new Dictionary<string,int> {{"Pangoro",675}},
            new Dictionary<string,int> {{"Panpour",515}},
            new Dictionary<string,int> {{"Pansage",511}},
            new Dictionary<string,int> {{"Pansear",513}},
            new Dictionary<string,int> {{"Paras",46}},
            new Dictionary<string,int> {{"Parasect",47}},
            new Dictionary<string,int> {{"Passimian",766}},
            new Dictionary<string,int> {{"Patrat",504}},
            new Dictionary<string,int> {{"Pawniard",624}},
            new Dictionary<string,int> {{"Pelipper",279}},
            new Dictionary<string,int> {{"Perrserker",863}},
            new Dictionary<string,int> {{"Persian",53}},
            new Dictionary<string,int> {{"Petilil",548}},
            new Dictionary<string,int> {{"Phanpy",231}},
            new Dictionary<string,int> {{"Phantump",708}},
            new Dictionary<string,int> {{"Pheromosa",795}},
            new Dictionary<string,int> {{"Phione",489}},
            new Dictionary<string,int> {{"Pichu",172}},
            new Dictionary<string,int> {{"Pidgeot",18}},
            new Dictionary<string,int> {{"Pidgeotto",17}},
            new Dictionary<string,int> {{"Pidgey",16}},
            new Dictionary<string,int> {{"Pidove",519}},
            new Dictionary<string,int> {{"Pignite",499}},
            new Dictionary<string,int> {{"Pikachu",25}},
            new Dictionary<string,int> {{"Pikipek",731}},
            new Dictionary<string,int> {{"Piloswine",221}},
            new Dictionary<string,int> {{"Pincurchin",871}},
            new Dictionary<string,int> {{"Pineco",204}},
            new Dictionary<string,int> {{"Pinsir",127}},
            new Dictionary<string,int> {{"Piplup",393}},
            new Dictionary<string,int> {{"Plusle",311}},
            new Dictionary<string,int> {{"Poipole",803}},
            new Dictionary<string,int> {{"Politoed",186}},
            new Dictionary<string,int> {{"Poliwag",60}},
            new Dictionary<string,int> {{"Poliwhirl",61}},
            new Dictionary<string,int> {{"Poliwrath",62}},
            new Dictionary<string,int> {{"Polteageist",855}},
            new Dictionary<string,int> {{"Ponyta",77}},
            new Dictionary<string,int> {{"Poochyena",261}},
            new Dictionary<string,int> {{"Popplio",728}},
            new Dictionary<string,int> {{"Porygon",137}},
            new Dictionary<string,int> {{"Porygon-Z",474}},
            new Dictionary<string,int> {{"Porygon2",233}},
            new Dictionary<string,int> {{"Primarina",730}},
            new Dictionary<string,int> {{"Primeape",57}},
            new Dictionary<string,int> {{"Prinplup",394}},
            new Dictionary<string,int> {{"Probopass",476}},
            new Dictionary<string,int> {{"Psyduck",54}},
            new Dictionary<string,int> {{"Pumpkaboo",710}},
            new Dictionary<string,int> {{"Pupitar",247}},
            new Dictionary<string,int> {{"Purrloin",509}},
            new Dictionary<string,int> {{"Purugly",432}},
            new Dictionary<string,int> {{"Pyroar",668}},
            new Dictionary<string,int> {{"Pyukumuku",771}},
            }
        },
        {"Q",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Quagsire",195}},
            new Dictionary<string,int> {{"Quilava",156}},
            new Dictionary<string,int> {{"Quilladin",651}},
            new Dictionary<string,int> {{"Qwilfish",211}},
            }
        },
        {"R",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Raboot",814}},
            new Dictionary<string,int> {{"Raichu",26}},
            new Dictionary<string,int> {{"Raikou",243}},
            new Dictionary<string,int> {{"Ralts",280}},
            new Dictionary<string,int> {{"Rampardos",409}},
            new Dictionary<string,int> {{"Rapidash",78}},
            new Dictionary<string,int> {{"Raticate",20}},
            new Dictionary<string,int> {{"Rattata",19}},
            new Dictionary<string,int> {{"Rayquaza",384}},
            new Dictionary<string,int> {{"Regice",378}},
            new Dictionary<string,int> {{"Regidrago",895}},
            new Dictionary<string,int> {{"Regieleki",894}},
            new Dictionary<string,int> {{"Regigigas",486}},
            new Dictionary<string,int> {{"Regirock",377}},
            new Dictionary<string,int> {{"Registeel",379}},
            new Dictionary<string,int> {{"Relicanth",369}},
            new Dictionary<string,int> {{"Remoraid",223}},
            new Dictionary<string,int> {{"Reshiram",643}},
            new Dictionary<string,int> {{"Reuniclus",579}},
            new Dictionary<string,int> {{"Rhydon",112}},
            new Dictionary<string,int> {{"Rhyhorn",111}},
            new Dictionary<string,int> {{"Rhyperior",464}},
            new Dictionary<string,int> {{"Ribombee",743}},
            new Dictionary<string,int> {{"Rillaboom",812}},
            new Dictionary<string,int> {{"Riolu",447}},
            new Dictionary<string,int> {{"Rockruff",744}},
            new Dictionary<string,int> {{"Roggenrola",524}},
            new Dictionary<string,int> {{"Rolycoly",837}},
            new Dictionary<string,int> {{"Rookidee",821}},
            new Dictionary<string,int> {{"Roselia",315}},
            new Dictionary<string,int> {{"Roserade",407}},
            new Dictionary<string,int> {{"Rotom",479}},
            new Dictionary<string,int> {{"Rowlet",722}},
            new Dictionary<string,int> {{"Rufflet",627}},
            new Dictionary<string,int> {{"Runerigus",867}},
            }
        },
        {"S",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Sableye",302}},
            new Dictionary<string,int> {{"Salamence",373}},
            new Dictionary<string,int> {{"Salandit",757}},
            new Dictionary<string,int> {{"Salazzle",758}},
            new Dictionary<string,int> {{"Samurott",503}},
            new Dictionary<string,int> {{"Sandaconda",844}},
            new Dictionary<string,int> {{"Sandile",551}},
            new Dictionary<string,int> {{"Sandshrew",27}},
            new Dictionary<string,int> {{"Sandslash",28}},
            new Dictionary<string,int> {{"Sandygast",769}},
            new Dictionary<string,int> {{"Sawk",539}},
            new Dictionary<string,int> {{"Sawsbuck",586}},
            new Dictionary<string,int> {{"Scatterbug",664}},
            new Dictionary<string,int> {{"Sceptile",254}},
            new Dictionary<string,int> {{"Scizor",212}},
            new Dictionary<string,int> {{"Scolipede",545}},
            new Dictionary<string,int> {{"Scorbunny",813}},
            new Dictionary<string,int> {{"Scrafty",560}},
            new Dictionary<string,int> {{"Scraggy",559}},
            new Dictionary<string,int> {{"Scyther",123}},
            new Dictionary<string,int> {{"Seadra",117}},
            new Dictionary<string,int> {{"Seaking",119}},
            new Dictionary<string,int> {{"Sealeo",364}},
            new Dictionary<string,int> {{"Seedot",273}},
            new Dictionary<string,int> {{"Seel",86}},
            new Dictionary<string,int> {{"Seismitoad",537}},
            new Dictionary<string,int> {{"Sentret",161}},
            new Dictionary<string,int> {{"Serperior",497}},
            new Dictionary<string,int> {{"Servine",496}},
            new Dictionary<string,int> {{"Seviper",336}},
            new Dictionary<string,int> {{"Sewaddle",540}},
            new Dictionary<string,int> {{"Sharpedo",319}},
            new Dictionary<string,int> {{"Shaymin",492}},
            new Dictionary<string,int> {{"Shedinja",292}},
            new Dictionary<string,int> {{"Shelgon",372}},
            new Dictionary<string,int> {{"Shellder",90}},
            new Dictionary<string,int> {{"Shellos",422}},
            new Dictionary<string,int> {{"Shelmet",616}},
            new Dictionary<string,int> {{"Shieldon",410}},
            new Dictionary<string,int> {{"Shiftry",275}},
            new Dictionary<string,int> {{"Shiinotic",756}},
            new Dictionary<string,int> {{"Shinx",403}},
            new Dictionary<string,int> {{"Shroomish",285}},
            new Dictionary<string,int> {{"Shuckle",213}},
            new Dictionary<string,int> {{"Shuppet",353}},
            new Dictionary<string,int> {{"Sigilyph",561}},
            new Dictionary<string,int> {{"Silcoon",266}},
            new Dictionary<string,int> {{"Silicobra",843}},
            new Dictionary<string,int> {{"Silvally",773}},
            new Dictionary<string,int> {{"Simipour",516}},
            new Dictionary<string,int> {{"Simisage",512}},
            new Dictionary<string,int> {{"Simisear",514}},
            new Dictionary<string,int> {{"Sinistea",854}},
            new Dictionary<string,int> {{"Sirfetch'd",865}},
            new Dictionary<string,int> {{"Sizzlipede",850}},
            new Dictionary<string,int> {{"Skarmory",227}},
            new Dictionary<string,int> {{"Skiddo",672}},
            new Dictionary<string,int> {{"Skiploom",188}},
            new Dictionary<string,int> {{"Skitty",300}},
            new Dictionary<string,int> {{"Skorupi",451}},
            new Dictionary<string,int> {{"Skrelp",690}},
            new Dictionary<string,int> {{"Skuntank",435}},
            new Dictionary<string,int> {{"Skwovet",819}},
            new Dictionary<string,int> {{"Slaking",289}},
            new Dictionary<string,int> {{"Slakoth",287}},
            new Dictionary<string,int> {{"Sliggoo",705}},
            new Dictionary<string,int> {{"Slowbro",80}},
            new Dictionary<string,int> {{"Slowking",199}},
            new Dictionary<string,int> {{"Slowpoke",79}},
            new Dictionary<string,int> {{"Slugma",218}},
            new Dictionary<string,int> {{"Slurpuff",685}},
            new Dictionary<string,int> {{"Smeargle",235}},
            new Dictionary<string,int> {{"Smoochum",238}},
            new Dictionary<string,int> {{"Sneasel",215}},
            new Dictionary<string,int> {{"Sneasler",903}},
            new Dictionary<string,int> {{"Snivy",495}},
            new Dictionary<string,int> {{"Snom",872}},
            new Dictionary<string,int> {{"Snorlax",143}},
            new Dictionary<string,int> {{"Snorunt",361}},
            new Dictionary<string,int> {{"Snover",459}},
            new Dictionary<string,int> {{"Snubbull",209}},
            new Dictionary<string,int> {{"Sobble",816}},
            new Dictionary<string,int> {{"Solgaleo",791}},
            new Dictionary<string,int> {{"Solosis",577}},
            new Dictionary<string,int> {{"Solrock",338}},
            new Dictionary<string,int> {{"Spearow",21}},
            new Dictionary<string,int> {{"Spectrier",897}},
            new Dictionary<string,int> {{"Spewpa",665}},
            new Dictionary<string,int> {{"Spheal",363}},
            new Dictionary<string,int> {{"Spinarak",167}},
            new Dictionary<string,int> {{"Spinda",327}},
            new Dictionary<string,int> {{"Spiritomb",442}},
            new Dictionary<string,int> {{"Spoink",325}},
            new Dictionary<string,int> {{"Spritzee",682}},
            new Dictionary<string,int> {{"Squirtle",7}},
            new Dictionary<string,int> {{"Stakataka",805}},
            new Dictionary<string,int> {{"Stantler",234}},
            new Dictionary<string,int> {{"Staraptor",398}},
            new Dictionary<string,int> {{"Staravia",397}},
            new Dictionary<string,int> {{"Starly",396}},
            new Dictionary<string,int> {{"Starmie",121}},
            new Dictionary<string,int> {{"Staryu",120}},
            new Dictionary<string,int> {{"Steelix",208}},
            new Dictionary<string,int> {{"Steenee",762}},
            new Dictionary<string,int> {{"Stonjourner",874}},
            new Dictionary<string,int> {{"Stoutland",508}},
            new Dictionary<string,int> {{"Stufful",759}},
            new Dictionary<string,int> {{"Stunfisk",618}},
            new Dictionary<string,int> {{"Stunky",434}},
            new Dictionary<string,int> {{"Sudowoodo",185}},
            new Dictionary<string,int> {{"Suicune",245}},
            new Dictionary<string,int> {{"Sunflora",192}},
            new Dictionary<string,int> {{"Sunkern",191}},
            new Dictionary<string,int> {{"Surskit",283}},
            new Dictionary<string,int> {{"Swablu",333}},
            new Dictionary<string,int> {{"Swadloon",541}},
            new Dictionary<string,int> {{"Swalot",317}},
            new Dictionary<string,int> {{"Swampert",260}},
            new Dictionary<string,int> {{"Swanna",581}},
            new Dictionary<string,int> {{"Swellow",277}},
            new Dictionary<string,int> {{"Swinub",220}},
            new Dictionary<string,int> {{"Swirlix",684}},
            new Dictionary<string,int> {{"Swoobat",528}},
            new Dictionary<string,int> {{"Sylveon",700}},
            }
        },
        {"T",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Taillow",276}},
            new Dictionary<string,int> {{"Talonflame",663}},
            new Dictionary<string,int> {{"Tangela",114}},
            new Dictionary<string,int> {{"Tangrowth",465}},
            new Dictionary<string,int> {{"Tapu Bulu",787}},
            new Dictionary<string,int> {{"Tapu Fini",788}},
            new Dictionary<string,int> {{"Tapu Koko",785}},
            new Dictionary<string,int> {{"Tapu Lele",786}},
            new Dictionary<string,int> {{"Tauros",128}},
            new Dictionary<string,int> {{"Teddiursa",216}},
            new Dictionary<string,int> {{"Tentacool",72}},
            new Dictionary<string,int> {{"Tentacruel",73}},
            new Dictionary<string,int> {{"Tepig",498}},
            new Dictionary<string,int> {{"Terrakion",639}},
            new Dictionary<string,int> {{"Thievul",828}},
            new Dictionary<string,int> {{"Throh",538}},
            new Dictionary<string,int> {{"Thundurus",642}},
            new Dictionary<string,int> {{"Thwackey",811}},
            new Dictionary<string,int> {{"Timburr",532}},
            new Dictionary<string,int> {{"Tirtouga",564}},
            new Dictionary<string,int> {{"Togedemaru",777}},
            new Dictionary<string,int> {{"Togekiss",468}},
            new Dictionary<string,int> {{"Togepi",175}},
            new Dictionary<string,int> {{"Togetic",176}},
            new Dictionary<string,int> {{"Torchic",255}},
            new Dictionary<string,int> {{"Torkoal",324}},
            new Dictionary<string,int> {{"Tornadus",641}},
            new Dictionary<string,int> {{"Torracat",726}},
            new Dictionary<string,int> {{"Torterra",389}},
            new Dictionary<string,int> {{"Totodile",158}},
            new Dictionary<string,int> {{"Toucannon",733}},
            new Dictionary<string,int> {{"Toxapex",748}},
            new Dictionary<string,int> {{"Toxel",848}},
            new Dictionary<string,int> {{"Toxicroak",454}},
            new Dictionary<string,int> {{"Toxtricity",849}},
            new Dictionary<string,int> {{"Tranquill",520}},
            new Dictionary<string,int> {{"Trapinch",328}},
            new Dictionary<string,int> {{"Treecko",252}},
            new Dictionary<string,int> {{"Trevenant",709}},
            new Dictionary<string,int> {{"Tropius",357}},
            new Dictionary<string,int> {{"Trubbish",568}},
            new Dictionary<string,int> {{"Trumbeak",732}},
            new Dictionary<string,int> {{"Tsareena",763}},
            new Dictionary<string,int> {{"Turtonator",776}},
            new Dictionary<string,int> {{"Turtwig",387}},
            new Dictionary<string,int> {{"Tympole",535}},
            new Dictionary<string,int> {{"Tynamo",602}},
            new Dictionary<string,int> {{"Type: Null",772}},
            new Dictionary<string,int> {{"Typhlosion",157}},
            new Dictionary<string,int> {{"Tyranitar",248}},
            new Dictionary<string,int> {{"Tyrantrum",697}},
            new Dictionary<string,int> {{"Tyrogue",236}},
            new Dictionary<string,int> {{"Tyrunt",696}},
            }
        },
        {"U",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Umbreon",197}},
            new Dictionary<string,int> {{"Unfezant",521}},
            new Dictionary<string,int> {{"Unown",201}},
            new Dictionary<string,int> {{"Ursaluna",901}},
            new Dictionary<string,int> {{"Ursaring",217}},
            new Dictionary<string,int> {{"Urshifu",892}},
            new Dictionary<string,int> {{"Uxie",480}},
            }
        },
        {"V",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Vanillish",583}},
            new Dictionary<string,int> {{"Vanillite",582}},
            new Dictionary<string,int> {{"Vanilluxe",584}},
            new Dictionary<string,int> {{"Vaporeon",134}},
            new Dictionary<string,int> {{"Venipede",543}},
            new Dictionary<string,int> {{"Venomoth",49}},
            new Dictionary<string,int> {{"Venonat",48}},
            new Dictionary<string,int> {{"Venusaur",3}},
            new Dictionary<string,int> {{"Vespiquen",416}},
            new Dictionary<string,int> {{"Vibrava",329}},
            new Dictionary<string,int> {{"Victini",494}},
            new Dictionary<string,int> {{"Victreebel",71}},
            new Dictionary<string,int> {{"Vigoroth",288}},
            new Dictionary<string,int> {{"Vikavolt",738}},
            new Dictionary<string,int> {{"Vileplume",45}},
            new Dictionary<string,int> {{"Virizion",640}},
            new Dictionary<string,int> {{"Vivillon",666}},
            new Dictionary<string,int> {{"Volbeat",313}},
            new Dictionary<string,int> {{"Volcanion",721}},
            new Dictionary<string,int> {{"Volcarona",637}},
            new Dictionary<string,int> {{"Voltorb",100}},
            new Dictionary<string,int> {{"Vullaby",629}},
            new Dictionary<string,int> {{"Vulpix",37}},
            }
        },
        {"W",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Wailmer",320}},
            new Dictionary<string,int> {{"Wailord",321}},
            new Dictionary<string,int> {{"Walrein",365}},
            new Dictionary<string,int> {{"Wartortle",8}},
            new Dictionary<string,int> {{"Watchog",505}},
            new Dictionary<string,int> {{"Weavile",461}},
            new Dictionary<string,int> {{"Weedle",13}},
            new Dictionary<string,int> {{"Weepinbell",70}},
            new Dictionary<string,int> {{"Weezing",110}},
            new Dictionary<string,int> {{"Whimsicott",547}},
            new Dictionary<string,int> {{"Whirlipede",544}},
            new Dictionary<string,int> {{"Whiscash",340}},
            new Dictionary<string,int> {{"Whismur",293}},
            new Dictionary<string,int> {{"Wigglytuff",40}},
            new Dictionary<string,int> {{"Wimpod",767}},
            new Dictionary<string,int> {{"Wingull",278}},
            new Dictionary<string,int> {{"Wishiwashi",746}},
            new Dictionary<string,int> {{"Wobbuffet",202}},
            new Dictionary<string,int> {{"Woobat",527}},
            new Dictionary<string,int> {{"Wooloo",831}},
            new Dictionary<string,int> {{"Wooper",194}},
            new Dictionary<string,int> {{"Wormadam",413}},
            new Dictionary<string,int> {{"Wurmple",265}},
            new Dictionary<string,int> {{"Wynaut",360}},
            new Dictionary<string,int> {{"Wyrdeer",899}},
            }
        },
        {"X",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Xatu",178}},
            new Dictionary<string,int> {{"Xerneas",716}},
            new Dictionary<string,int> {{"Xurkitree",796}},
            }
        },
        {"Y",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Yamask",562}},
            new Dictionary<string,int> {{"Yamper",835}},
            new Dictionary<string,int> {{"Yanma",193}},
            new Dictionary<string,int> {{"Yanmega",469}},
            new Dictionary<string,int> {{"Yungoos",734}},
            new Dictionary<string,int> {{"Yveltal",717}},
            }
        },
        {"Z",new List<Dictionary<string,int>> {
            new Dictionary<string,int> {{"Zacian",888}},
            new Dictionary<string,int> {{"Zamazenta",889}},
            new Dictionary<string,int> {{"Zangoose",335}},
            new Dictionary<string,int> {{"Zapdos",145}},
            new Dictionary<string,int> {{"Zarude",893}},
            new Dictionary<string,int> {{"Zebstrika",523}},
            new Dictionary<string,int> {{"Zekrom",644}},
            new Dictionary<string,int> {{"Zeraora",807}},
            new Dictionary<string,int> {{"Zigzagoon",263}},
            new Dictionary<string,int> {{"Zoroark",571}},
            new Dictionary<string,int> {{"Zorua",570}},
            new Dictionary<string,int> {{"Zubat",41}},
            new Dictionary<string,int> {{"Zweilous",634}},
            new Dictionary<string,int> {{"Zygarde",718}},
            }
        }
    };
    
    
    public static List<Dictionary<string,int>> GetPokemonByLetter(string letter){
        return pokemonList[letter];
    }
   
}
